### PR TITLE
Created a README.md to explain file mappings.

### PR DESCRIPTION
**Pull request by ahcox**
This should let any new visitors know where the file they are editing will finally be displayed.

### CODE REVIEW

**Comment by outofcontrol** [comment]
Should we have one README.md per directory inside /api, or would it make more sense to have a single README.md just above /api that defines file mappings? Considering that most of the APIs will have the same mappings.

**Comment by ahcox** [comment]
> Should we have one README.md per directory inside /api, or would it make more sense to have a single README.md just above /api that defines file mappings? Considering that most of the APIs will have the same mappings.

I see the considerable uniformity of structure (see below). My point of view is of someone interested in Vulkan and not in everything else in the repository. With this patch a potential Vulkan site contributor goes to https://github.com/KhronosGroup/Khronosdotorg/tree/master/api/vulkan and sees everything they need to get started. It also lets me link from the README.md directly to the page rather than giving an English language description of how to navigate there on khronos.org. To give those links one level up involves making a list there with one entry per API anyway.

    .
    ├── api
    │   ├── collada
    │   │   └── bluebox.md
    │   ├── dataformat
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── egl
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── gltf
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── opencl
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── opengl
    │   │   └── bluebox.md
    │   ├── opengles
    │   │   ├── 1_x
    │   │   │   └── bluebox.md
    │   │   ├── 2_x
    │   │   │   └── bluebox.md
    │   │   ├── 3_x
    │   │   │   └── bluebox.md
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── openglsc
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── openkcam
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── openkode
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── openmax
    │   │   ├── al
    │   │   │   └── bluebox.md
    │   │   ├── bluebox.md
    │   │   ├── dl
    │   │   │   └── bluebox.md
    │   │   ├── il
    │   │   │   └── bluebox.md
    │   │   └── resources.md
    │   ├── openml
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── opensles
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── openvg
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── openvx
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── openwf
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── README.md
    │   ├── spir
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── streaminput
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── sycl
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   ├── vulkan
    │   │   ├── bluebox.md
    │   │   └── resources.md
    │   └── webcl
    │       ├── bluebox.md
    │       └── resources.md
    └── README.md

**Comment by ahcox** [comment]
Will try to contribute something else in the future.

**Comment by outofcontrol** [comment]
Thanks Andrew. I'm going to approve this PR shortly. I'll add README.md files for each API directory  with the correct information as well.

**Pull request closed without merging**
